# Site settings
title: "Exelearning Theme" 
description: "Module 1 | exelearning"
url: ""
author:
  name: "Federico Arias"
  email: "federicoariasr@gmail.com"

# Build settings
baseurl: "/" 
markdown: redcarpet 
extensions: [fenced_code_blocks]
source: .
destination: ./_site
permalink: /:title
paginate: 12
paginate_path: /page:num/
exclude: [bower_components/, node_modules/, src/]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
math: false
