# Site settings
title: "{ federico-arias }"
baseUrl: "https://federico-arias.github.io"
disqusShortname: federico-arias-disqus
googleAnalytics: UA-127821516-1
pygmentsCodeFences: true
theme: huguito1
sectionPagesMenu:  "main"
menu:
  foo:
  - name: hire me
    url: /hireme
    weight: -100
  - identifier: about
    name: about
    url: /about
    weight: -110
  - name: home
    url:
    weight: -200
paginate: 6
metaDataFormat: "yaml"
publishDir: "./"
disableKinds:
    - taxonomy
    - taxonomyTerm
